-- ============================================================
-- 0021_interview_prep_seed — 2026-09-22
-- Interview Prep launched as an empty, teacher-authored CRUD with no
-- starter content. This seeds five categories and four genuine,
-- 200+ word topic explanations each (20 total) — real "important
-- topics" reading material, not short Q&A trivia. `created_by` is
-- left null (system-authored, not tied to any one teacher account),
-- which the schema already allows.
--
-- Idempotent without a new unique constraint: categories key off the
-- existing unique `slug`; each topic insert is guarded by a
-- `where not exists` check on (category, topic name) instead of an
-- `on conflict`, so this is safe to run more than once without
-- risking a constraint-violation failure against whatever data may
-- already exist in a live project.
-- ============================================================

insert into interview_categories (name, slug, description, icon, display_order)
values
  ('OOP Concepts', 'oop', 'The four pillars of object-oriented programming, explained with real examples.', 'Boxes', 0),
  ('DBMS', 'dbms', 'Core relational database concepts every interview touches on.', 'Database', 1),
  ('Operating Systems', 'operating-systems', 'Processes, memory, deadlock, and scheduling — OS fundamentals.', 'Cpu', 2),
  ('Computer Networks', 'networking', 'How data actually moves between machines.', 'Network', 3),
  ('System Design', 'system-design', 'Building blocks for designing systems at scale.', 'Server', 4)
on conflict (slug) do nothing;

-- ---------- OOP Concepts ----------

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'Encapsulation', $$Encapsulation is the practice of bundling an object's data (its fields) together with the methods that operate on that data, while restricting direct access to some of the object's internal state. In practice, this means marking fields as private and exposing controlled access through public getter and setter methods, so the class itself decides what values are valid rather than trusting every caller to enforce that discipline. For example, a BankAccount class might keep its balance field private and only allow it to change through a withdraw() method that checks for sufficient funds — no external code can set balance directly to an invalid negative number. The core benefit is that the internal implementation can change freely (switching from an array to a linked list, say) without breaking any code that depends on the class's public interface, as long as that interface's behavior stays the same. This is often called "information hiding," and it's what makes large codebases maintainable: a bug in how a class stores its data is contained to that class, not scattered across every place that touches it. Encapsulation also improves security, since sensitive fields can be made entirely inaccessible from outside, and it reduces coupling between classes, since consumers only need to know a class's public contract, not its internals. Most languages support this directly with access modifiers (private, protected, public in Java/C++, or a leading underscore convention in Python), and getters/setters can also add validation, logging, or lazy computation transparently, all invisible to the caller.$$, 'medium'
from interview_categories c where c.slug = 'oop'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'Encapsulation');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'Inheritance', $$Inheritance lets one class (the subclass or derived class) acquire the fields and methods of another (the superclass or base class), establishing an "is-a" relationship between them. A Car class might inherit from a more general Vehicle class, automatically getting fields like speed and methods like accelerate() without redefining them, while adding or overriding behavior specific to cars. The main value is code reuse: common behavior is written once in the base class and shared by every subclass, instead of being copy-pasted everywhere. It also enables polymorphism — code written against the base type (a function that takes a Vehicle) can transparently work with any subclass (Car, Truck, Motorcycle) without knowing which one it actually received at runtime. Most object-oriented languages support single inheritance (one direct parent) for classes, though some allow multiple inheritance of behavior through interfaces or traits, which avoids the "diamond problem" ambiguity that comes from inheriting the same method from two different parents. A common interview pitfall is overusing inheritance where composition would be more appropriate: inheritance creates a tight, permanent coupling between classes (a subclass breaks if its parent's implementation changes), so the standard guidance — "favor composition over inheritance" — suggests reaching for inheritance only for genuine is-a relationships, and building more flexible behavior by having a class hold a reference to another (a has-a relationship) in most other cases.$$, 'medium'
from interview_categories c where c.slug = 'oop'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'Inheritance');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'Polymorphism', $$Polymorphism, literally "many forms," is the ability for the same operation or method call to behave differently depending on the actual object it's invoked on. There are two main kinds. Compile-time (or static) polymorphism is achieved through method overloading — defining multiple methods with the same name but different parameter lists, so the compiler picks the right one based on the arguments at compile time. Runtime (or dynamic) polymorphism is achieved through method overriding: a subclass provides its own implementation of a method already defined in its superclass, and which version actually runs is decided at runtime based on the object's real type, not the type of the reference pointing to it. This is what makes a line like `Animal a = new Dog(); a.makeSound();` call Dog's makeSound() even though `a` is declared as an Animal — the runtime looks up the method on the object's actual class via a mechanism usually called "dynamic dispatch" or a virtual method table. Polymorphism is central to writing extensible code: a function that processes a list of Shape objects and calls shape.area() doesn't need to know or care whether each shape is a Circle, Square, or Triangle — each object's own area() implementation runs correctly. This is also the foundation of many design patterns (Strategy, Template Method, Visitor) and is why interfaces and abstract classes are so useful: they let you program against a contract rather than a concrete implementation.$$, 'medium'
from interview_categories c where c.slug = 'oop'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'Polymorphism');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'Abstraction', $$Abstraction means exposing only the essential features of an object or system while hiding the complex implementation details behind a simpler interface. When you press a car's accelerator pedal, you don't need to know how fuel injection, combustion timing, or the transmission actually work — you just need the car to speed up. In object-oriented programming, abstraction is typically implemented through abstract classes and interfaces: an abstract class can declare method signatures without providing a body, forcing every concrete subclass to supply its own implementation, while an interface goes further and defines a pure contract with no implementation at all. This lets you design systems around "what something does" rather than "how it does it," which is exactly what makes large systems manageable — a caller depends only on a stable, simple interface, while the implementation behind it is free to change. Abstraction is often confused with encapsulation, since both involve "hiding" something, but they solve different problems: encapsulation hides an object's internal state to protect its integrity, while abstraction hides implementation complexity to reduce what a caller needs to think about. A practical example: a List interface hides whether the underlying implementation is an array-backed list or a node-backed linked list — code written against List works with either, and the choice of implementation can be swapped later with zero changes to the calling code.$$, 'medium'
from interview_categories c where c.slug = 'oop'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'Abstraction');

-- ---------- DBMS ----------

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'Normalization', $$Normalization is the process of organizing a relational database's tables and columns to reduce data redundancy and avoid update anomalies — situations where the same fact is stored in multiple places and can go out of sync. It's done by progressively applying a series of rules called "normal forms." First Normal Form (1NF) requires every column to hold atomic (indivisible) values and every row to be unique — no repeating groups or comma-separated lists crammed into one field. Second Normal Form (2NF) builds on 1NF by requiring every non-key column to depend on the entire primary key, not just part of it — relevant when a table has a composite key. Third Normal Form (3NF) goes further, requiring that non-key columns depend only on the primary key and not on each other (eliminating "transitive dependencies") — for example, storing both a customer's city and their zip code in an orders table is a 3NF violation, since zip code determines city, not the order. Most production schemas aim for 3NF or the slightly stricter Boyce-Codd Normal Form (BCNF) as a practical target. The tradeoff is that normalization, while eliminating redundancy and anomalies, tends to increase the number of tables and requires more joins to reconstruct a full picture of an entity — which is why some read-heavy systems deliberately denormalize (reintroduce some redundancy) for performance, accepting the anomaly risk in exchange for fewer joins on hot query paths. Knowing when to normalize versus denormalize is a common system-design interview discussion.$$, 'medium'
from interview_categories c where c.slug = 'dbms'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'Normalization');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'ACID Properties', $$ACID is an acronym describing four guarantees a database transaction should provide to keep data reliable, especially when multiple operations or multiple users touch the database concurrently. Atomicity means a transaction is all-or-nothing — if a transfer debits one account and credits another, either both operations succeed or neither does; a failure partway through rolls back everything, so the database never ends up with money "in transit" and lost. Consistency means a transaction takes the database from one valid state to another, never violating defined rules like constraints, foreign keys, or triggers. Isolation means concurrent transactions don't interfere with each other's intermediate states — from each transaction's point of view, it appears to run as if it were the only one happening, even though the database may actually be interleaving many transactions for performance; different isolation levels (read uncommitted, read committed, repeatable read, serializable) trade off strictness against performance. Durability means once a transaction commits, its changes survive even a crash immediately afterward — typically guaranteed by writing to a persistent transaction log before acknowledging the commit. Together, ACID is what lets you reason about a database transactionally instead of worrying about partial failures or race conditions corrupting your data; it's the standard most relational databases (PostgreSQL, MySQL, Oracle) are built around, in contrast to many NoSQL systems that relax some of these guarantees in exchange for scalability.$$, 'medium'
from interview_categories c where c.slug = 'dbms'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'ACID Properties');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'Indexing', $$A database index is a separate data structure — usually a B-tree or a hash table — that stores a sorted or otherwise fast-to-search copy of one or more columns' values, each paired with a pointer back to the full row. Without an index, looking up a row by a column's value requires a full table scan: checking every single row, an O(n) operation that gets slower as the table grows. With an index on that column, the database can instead do something closer to a binary search, typically O(log n), jumping straight to the matching rows — the same benefit binary search has over linear search, just applied to database rows instead of an in-memory array. The tradeoff is that an index isn't free: it takes extra disk space, and every INSERT, UPDATE, or DELETE on the indexed column has to also update the index, which slows down writes. This is why indexes should be added deliberately — typically on columns used often in WHERE clauses, JOIN conditions, or ORDER BY, not blindly on every column. A primary key is automatically indexed by most databases; other indexes (called secondary indexes) are added explicitly. Composite indexes (spanning multiple columns) can speed up queries that filter on several columns together, but the column order in the index matters — a composite index on (a, b) helps queries filtering on a alone or a AND b, but not on b alone.$$, 'medium'
from interview_categories c where c.slug = 'dbms'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'Indexing');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'Types of SQL Joins', $$A JOIN combines rows from two or more tables based on a related column between them, and the type of join determines which rows survive when a match isn't found on one side. An INNER JOIN returns only the rows that have a matching value in both tables — if an order references a customer_id that doesn't exist in the customers table, that order simply doesn't appear in the result. A LEFT (OUTER) JOIN returns every row from the left table regardless of whether a match exists on the right, filling in NULLs for the right table's columns when there's no match — useful for "show me all customers, including ones with zero orders." A RIGHT (OUTER) JOIN is the mirror image, keeping every row from the right table instead. A FULL (OUTER) JOIN keeps every row from both tables, matching where possible and filling NULLs on whichever side has no match — effectively a LEFT JOIN and a RIGHT JOIN combined. A CROSS JOIN produces the Cartesian product of both tables — every row from the first paired with every row from the second — with no matching condition at all, which is rarely what you want unless you're deliberately generating combinations. Interviewers often ask you to reason about which rows survive a given join type on a small example table, since getting INNER vs. LEFT confused is one of the most common real-world SQL bugs.$$, 'medium'
from interview_categories c where c.slug = 'dbms'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'Types of SQL Joins');

-- ---------- Operating Systems ----------

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'Process vs Thread', $$A process is an independent, running instance of a program, with its own private memory space (code, data, heap, stack) that the operating system isolates from every other process — one process crashing or corrupting its memory doesn't directly affect another. A thread is a unit of execution within a process; a single process can have multiple threads, and all threads in the same process share that process's memory space (heap and global data), though each thread still gets its own stack and program counter. This shared-memory model is exactly why threads are lighter-weight than processes — creating a thread doesn't require setting up a whole new address space, just a new stack and scheduling entry, so context-switching between threads is faster than switching between processes. It's also exactly why threading is riskier: since threads share memory, one thread writing to shared data while another reads it, without proper synchronization via locks, mutexes, or semaphores, causes race conditions and can corrupt state in ways that are notoriously hard to reproduce and debug. Inter-process communication (IPC), by contrast, has to go through explicit OS-provided channels — pipes, sockets, shared memory segments, message queues — precisely because processes don't share memory by default. A practical way to think about it: use multiple processes when you want strong isolation and fault tolerance, and use multiple threads within one process when you want to parallelize work that needs to share data efficiently.$$, 'medium'
from interview_categories c where c.slug = 'operating-systems'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'Process vs Thread');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'Deadlock', $$A deadlock is a state where two or more processes (or threads) are each waiting on a resource held by another, forming a cycle where none of them can ever proceed — every participant is permanently blocked. The classic illustration is two processes each holding one of two required locks: process A holds lock 1 and waits for lock 2, while process B holds lock 2 and waits for lock 1; neither will ever release what it's holding, so both wait forever. Four conditions must all hold simultaneously for a deadlock to be possible, known as the Coffman conditions: mutual exclusion (a resource can only be held by one process at a time), hold and wait (a process holding one resource can request another), no preemption (a resource can't be forcibly taken away — it must be released voluntarily), and circular wait (a cycle of processes each waiting on the next). Breaking any one of these conditions prevents deadlock, which is exactly how most practical solutions work: enforcing a strict, global order in which locks must always be acquired (eliminates circular wait), using timeouts so a waiting process gives up and releases what it holds, or having the OS detect a cycle in a resource-allocation graph after the fact and forcibly kill or roll back one of the participants. Operating systems and database systems both deal with deadlock, though databases typically favor detection-and-rollback (aborting one transaction) over prevention, since transactions are expected to be retryable.$$, 'hard'
from interview_categories c where c.slug = 'operating-systems'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'Deadlock');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'Virtual Memory', $$Virtual memory is an abstraction that gives each process the illusion of having its own large, contiguous, private address space, even though the actual physical RAM is smaller and shared across every running process. The operating system, with hardware support from the Memory Management Unit (MMU), maps each process's virtual addresses to real physical addresses (or to disk) through page tables — memory is divided into fixed-size chunks called pages (commonly 4KB), and each page can be mapped independently. This indirection enables several powerful capabilities. First, isolation: two processes can both believe they own address 0x1000, but the MMU maps each to a completely different physical location, so neither can accidentally read or corrupt the other's memory. Second, it lets the total memory used by all processes exceed physical RAM: pages that haven't been used recently can be "swapped out" to disk, and brought back in ("paged in") on demand when accessed again — a page fault. Third, it enables memory-mapped files and lazy loading, since a page doesn't have to be backed by real content until it's actually touched. The tradeoff is performance: if a system doesn't have enough RAM and is constantly swapping pages in and out (called "thrashing"), performance collapses since disk access is orders of magnitude slower than RAM. Virtual memory is one of the most load-bearing abstractions in modern operating systems, underlying everything from process isolation to how executables are loaded.$$, 'hard'
from interview_categories c where c.slug = 'operating-systems'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'Virtual Memory');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'CPU Scheduling', $$CPU scheduling is how an operating system decides which of several ready-to-run processes or threads gets the CPU next, since on a system with more runnable tasks than CPU cores, most of them have to wait their turn. The scheduler's goal is usually to balance several competing priorities: maximizing throughput, minimizing turnaround time, minimizing waiting time, and — for interactive systems — keeping response time low so the system feels snappy. Several classic algorithms illustrate the tradeoffs. First-Come-First-Served (FCFS) is the simplest — process the queue in arrival order — but a single long task can make everything behind it wait a long time (the "convoy effect"). Shortest Job First (SJF) minimizes average waiting time by always running the shortest task next, but requires knowing task lengths in advance and can starve long tasks indefinitely. Round Robin gives each process a small fixed time slice (a "quantum") before moving to the next, cycling through repeatedly — this is fair and keeps the system responsive, but too short a quantum wastes time on context-switching overhead, while too long a quantum degrades toward FCFS. Priority scheduling runs the highest-priority task first, but risks starving low-priority ones unless combined with "aging" (gradually raising a waiting task's priority over time). Real operating systems (like Linux's CFS) use more sophisticated hybrid approaches, but understanding these classic algorithms is the foundation interviewers expect.$$, 'medium'
from interview_categories c where c.slug = 'operating-systems'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'CPU Scheduling');

-- ---------- Computer Networks ----------

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'OSI Model', $$The OSI (Open Systems Interconnection) model is a conceptual, seven-layer framework describing how data moves from an application on one machine to an application on another, with each layer handling a distinct responsibility and talking only to the layers directly above and below it. From bottom to top: the Physical layer deals with raw bits over a medium; the Data Link layer packages bits into frames and handles node-to-node delivery on the same local network, including MAC addressing (this is where switches operate); the Network layer handles logical addressing and routing between different networks (IP addresses live here, and this is where routers operate); the Transport layer provides end-to-end communication with features like reliability and ordering (TCP) or a lighter, connectionless option (UDP); the Session layer manages and maintains connections between applications; the Presentation layer handles data translation, encryption, and compression so both ends agree on format; and the Application layer is where actual user-facing protocols live (HTTP, FTP, SMTP). In practice, real-world networking mostly follows the simpler four-layer TCP/IP model (Link, Internet, Transport, Application), which collapses several OSI layers together — but the OSI model remains the standard teaching and reference framework because it cleanly separates concerns and makes it easy to reason about where a given protocol or piece of hardware fits. Interviewers often use it to check whether a candidate understands that "the network" isn't one monolithic thing but a stack of independent, cooperating layers, each solving one problem.$$, 'medium'
from interview_categories c where c.slug = 'networking'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'OSI Model');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'TCP vs UDP', $$TCP (Transmission Control Protocol) and UDP (User Datagram Protocol) are both transport-layer protocols, but they make very different tradeoffs between reliability and speed. TCP is connection-oriented: before any data is sent, both ends perform a three-way handshake (SYN, SYN-ACK, ACK) to establish a connection. Once established, TCP guarantees reliable, ordered delivery — every packet is acknowledged, lost packets are automatically retransmitted, and packets that arrive out of order are reassembled in the correct sequence before being handed to the application. It also does flow control and congestion control, throttling the send rate to match what the receiver and network can handle. All of this reliability comes at the cost of overhead and latency. UDP, by contrast, is connectionless: there's no handshake, no acknowledgment, no guaranteed delivery, and no guaranteed ordering — a packet ("datagram") is just fired off, and it's entirely up to the application to handle loss or reordering if it cares. This makes UDP significantly faster and lower-overhead, which is exactly why it's used for real-time applications like video calls, live streaming, and online gaming, where a dropped or late packet is better handled by simply skipping it than by TCP's approach of pausing everything to retransmit and reorder. The general rule of thumb: use TCP when correctness and completeness matter more than speed, and UDP when speed and low latency matter more than perfect delivery.$$, 'medium'
from interview_categories c where c.slug = 'networking'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'TCP vs UDP');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'DNS (Domain Name System)', $$DNS (Domain Name System) is the internet's distributed system for translating human-readable domain names, like example.com, into the numeric IP addresses that computers actually use to route traffic to each other — it's often described as "the phone book of the internet." When a browser needs to resolve a domain, it typically first checks its local cache, then asks a DNS resolver (often run by your ISP or a public service), which itself may have the answer cached. If not, the resolver queries a hierarchy of servers: first a root server (which knows where to find servers for top-level domains like .com), then a TLD server for .com (which knows where to find the authoritative server for example.com), and finally the authoritative name server for example.com itself, which returns the actual IP address. This chain is usually completed in milliseconds and heavily cached at every level — each DNS record has a TTL (time-to-live) controlling how long it can be cached before it must be looked up again, which is why DNS changes can take time to "propagate" globally. DNS also supports several record types beyond the basic A record (IPv4 address): AAAA (IPv6 address), CNAME (an alias pointing to another domain), MX (mail server), and TXT (arbitrary text, often used for domain verification or email security like SPF/DKIM).$$, 'easy'
from interview_categories c where c.slug = 'networking'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'DNS (Domain Name System)');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'HTTP vs HTTPS', $$HTTP (HyperText Transfer Protocol) is the application-layer protocol that web browsers and servers use to request and send resources — pages, images, API responses — and it's fundamentally a plain-text, request-response protocol: a client sends a request with a method (GET, POST, etc.), headers, and optionally a body, and the server replies with a status code, headers, and a body. The problem with plain HTTP is that everything travels unencrypted, so anyone in a position to intercept the traffic can read or even modify it in transit. HTTPS (HTTP Secure) solves this by running HTTP over TLS (Transport Layer Security, the successor to SSL), which encrypts the connection before any HTTP data is exchanged. This involves a TLS handshake where the server presents a certificate (issued by a trusted Certificate Authority) proving its identity, and both sides negotiate a shared encryption key using asymmetric cryptography, which is then used for fast symmetric encryption of the actual data for the rest of the session. This gives HTTPS three key properties HTTP lacks: confidentiality (data can't be read in transit), integrity (data can't be silently modified), and authentication (you can verify you're actually talking to the real example.com, not an impostor). Modern browsers now flag plain HTTP sites as "not secure," and HTTPS is effectively the default expectation for any production website today.$$, 'easy'
from interview_categories c where c.slug = 'networking'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'HTTP vs HTTPS');

-- ---------- System Design ----------

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'Load Balancing', $$A load balancer sits in front of a pool of backend servers and distributes incoming requests across them, so no single server gets overwhelmed while others sit idle — it's one of the most fundamental building blocks for scaling a system beyond what one machine can handle. Beyond just spreading load, a load balancer also improves availability: it can continuously health-check backend servers and automatically stop routing traffic to any that are down or unresponsive, so a single server failure doesn't take down the whole system. Common distribution strategies include round robin (cycle through servers in order), least connections (send the next request to whichever server currently has the fewest active connections), and IP hash (route a given client consistently to the same server, useful when session state is tied to a specific machine). Load balancers can operate at different layers: a Layer 4 load balancer works at the transport layer, routing based on IP and port without inspecting the actual content, which is fast but limited; a Layer 7 load balancer works at the application layer, and can make smarter routing decisions based on the actual HTTP request — the URL path, headers, or cookies. In larger systems, load balancers themselves are often deployed in redundant pairs to avoid becoming a single point of failure, and can be layered — a global load balancer directing traffic to regional load balancers, which then distribute within a region.$$, 'medium'
from interview_categories c where c.slug = 'system-design'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'Load Balancing');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'Caching', $$Caching means storing a copy of expensive-to-compute or expensive-to-fetch data somewhere faster to access, so repeated requests for the same thing can be served quickly instead of redoing the original work every time. The core insight that makes caching effective is locality of reference — in most real systems, a small subset of data is accessed far more often than the rest (the "hot" data), so caching just that subset captures most of the benefit. Caches can live at many layers of a system: in the browser, at a CDN (edge servers close to users caching static content), in-memory within an application, or as a dedicated caching layer in front of a database (like Redis or Memcached, caching query results so the database isn't hit on every read). The two hardest problems in caching are eviction and invalidation. Eviction is about what to remove when the cache is full — common policies include LRU (Least Recently Used) and LFU (Least Frequently Used). Invalidation is about making sure the cache doesn't serve stale data once the underlying source changes — approaches include setting a TTL so entries expire automatically, or explicitly invalidating/updating the cache entry whenever the underlying data is written (write-through or write-behind caching). Getting invalidation wrong is famously one of the trickiest problems in software — as the old joke goes, "there are only two hard things in computer science: cache invalidation and naming things."$$, 'medium'
from interview_categories c where c.slug = 'system-design'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'Caching');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'Horizontal vs Vertical Scaling', $$Scaling a system means increasing its capacity to handle more load, and there are two fundamentally different ways to do it. Vertical scaling ("scaling up") means making a single machine more powerful — adding more CPU, RAM, or faster disks to the existing server. It's simple, since the application usually needs no architectural changes to take advantage of more resources, but it has a hard ceiling: there's a maximum amount of CPU and RAM any single machine can physically have, and high-end hardware gets disproportionately expensive as you approach that ceiling. It's also a single point of failure — if that one powerful machine goes down, the whole system goes down with it. Horizontal scaling ("scaling out") means adding more machines and distributing load across all of them, typically behind a load balancer. This avoids the hard ceiling of vertical scaling and improves fault tolerance, since the failure of one server out of many doesn't take down the whole system. The tradeoff is complexity: the application has to be designed to run correctly across multiple machines, which raises real challenges around state (where does session data live if requests can hit any server?), data consistency across servers, and coordination. Most large-scale systems ultimately rely on horizontal scaling for their core capacity, while still using vertical scaling for components that are hard to distribute, like a primary database.$$, 'medium'
from interview_categories c where c.slug = 'system-design'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'Horizontal vs Vertical Scaling');

insert into interview_questions (category_id, question, answer, difficulty)
select c.id, 'Database Sharding', $$Sharding is a technique for horizontally scaling a database by splitting its data across multiple separate database instances (shards), where each shard holds a distinct subset of the overall dataset, rather than every server holding a full copy. This is different from replication, which keeps identical full copies of the data on multiple servers for redundancy and read scaling — sharding instead partitions the data itself, so the combined shards together hold the complete dataset, and each individual shard holds less. The central design decision in sharding is choosing a shard key — the field used to decide which shard a given row belongs to. A common approach is hashing a key like user_id and using the hash to pick a shard, which tends to distribute data evenly; another is range-based sharding (e.g., users A-M on shard 1, N-Z on shard 2), which is simpler to reason about but can lead to uneven load if the ranges aren't naturally balanced. Sharding solves a real scaling problem — a single database server has a ceiling on storage and query throughput — but it introduces serious complexity: queries that need to join or aggregate data across shards become much harder and slower, a bad shard key choice can create "hot shards," and resharding when you add more shards later is a genuinely difficult operational problem. For this reason, sharding is usually treated as a scaling technique of last resort, reached for only after simpler options like caching, indexing, and read replicas have been exhausted.$$, 'hard'
from interview_categories c where c.slug = 'system-design'
and not exists (select 1 from interview_questions q where q.category_id = c.id and q.question = 'Database Sharding');
